=== Wander29/TPSI/UDL1/XML/04_Automobile_DTD[26-09-17]/Auto_DTD.dtd
<!ELEMENT automobile (nome, marca, cilindrata, prezzo, dimensioni, tipologia_motore, kw, porte)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT cilindrata (#PCDATA)>
<!ELEMENT prezzo (#PCDATA)>
<!ELEMENT dimensioni (lunghezza, larghezza, altezza)>
    <!ELEMENT lunghezza (#PCDATA)>
    <!ELEMENT larghezza (#PCDATA)>
    <!ELEMENT altezza (#PCDATA)>
<!ELEMENT tipologia_motore (#PCDATA)>
<!ELEMENT kw (#PCDATA)>
<!ELEMENT porte (#PCDATA)>

=== Wander29/TPSI/UDL1/XML/04_Automobile_DTD[26-09-17]/Automobile.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE automobile SYSTEM "Auto_DTD.dtd"> <!-- root_element = primo tag XML (elemento radice del file XML) -->
<automobile>
    <nome>punto e virgola</nome>
    <marca>fiat</marca>
    <cilindrata>2099</cilindrata>
    <prezzo>3000</prezzo>
    <dimensioni>
         <lunghezza>350</lunghezza>
         <larghezza>180</larghezza>	
         <altezza>150</altezza>
    </dimensioni>	
    <tipologia_motore>Diesel</tipologia_motore>	
    <kw>52</kw>	
    <porte>8</porte>		
</automobile>
